#pragma kernel CSMain

#include "GammaLinear.hlsl"

Texture2D<float4> _BaseTex;
SamplerState sampler_BaseTex;
Texture2D<float4> _LayerTex;
SamplerState sampler_LayerTex;

RWTexture2D<float4> _TargetTex;

int2 _CanvasSize;

float2 _BaseTexScale;
float2 _LayerTexScale;

float _LayerOpacity;
int _LayerBlendMode;

float3 BlendColor(float3 baseRgb, float3 layerRgb, int blendMode)
{
    if (blendMode == 1)
    {
        return baseRgb * layerRgb;
    }

    if (blendMode == 2)
    {
        return 1.0 - (1.0 - baseRgb) * (1.0 - layerRgb);
    }

    if (blendMode == 3)
    {
        return saturate(baseRgb + layerRgb);
    }

    if (blendMode == 4)
    {
        return saturate(baseRgb - layerRgb);
    }

    if (blendMode == 5)
    {
        return min(baseRgb, layerRgb);
    }

    if (blendMode == 6)
    {
        return max(baseRgb, layerRgb);
    }

    if (blendMode == 7)
    {
        return abs(baseRgb - layerRgb);
    }

    if (blendMode == 8)
    {
        float3 low = 2.0 * baseRgb * layerRgb;
        float3 high = 1.0 - 2.0 * (1.0 - baseRgb) * (1.0 - layerRgb);
        return lerp(high, low, step(baseRgb, 0.5));
    }

    return layerRgb;
}

float4 BlendWithMode(float4 baseCol, float4 layerCol, int blendMode)
{
    float3 blendedRgb = BlendColor(baseCol.rgb, layerCol.rgb, blendMode);
    float3 rgb = lerp(baseCol.rgb, blendedRgb, layerCol.a);
    float a = layerCol.a + baseCol.a * (1 - layerCol.a);

    return float4(rgb, a);
}

[numthreads(16, 16, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 uv = (id.xy + 0.5) / _CanvasSize;
    
    float4 baseCol = _BaseTex.SampleLevel(sampler_BaseTex, uv, 0);

    float4 layerCol = _LayerTex.SampleLevel(sampler_LayerTex, uv, 0);

    layerCol.a = layerCol.a * _LayerOpacity;

    float4 blended = BlendWithMode(baseCol, layerCol, _LayerBlendMode);

    _TargetTex[id.xy] = blended;
}
