#pragma kernel CSMain

#include "GammaLinear.hlsl"
#include "ColorConvert.hlsl"
#include "BalanceModeShader.hlsl"
#include "AdvancedColorShader.hlsl"

Texture2D<float4> _SourceTex;
RWTexture2D<float4> _TargetTex;

int _UseMask;
Texture2D<float4> _MaskTex;
float2 _MaskTexScale;
int _MaskSelectionType;
bool _IsBackgroundTransparent;

int _ColorAdjustmentConfigurationEnabled;

int _ColorMode;

int4 _NormalSourceColor;
int4 _NormalTargetColor;

float _V1Weight;
float _V1Minimum;

float _V2Weight;
float _V2Radius;
float _V2Minimum;
bool _V2IncludeOutside;

Texture2D<float4> _V3Gradient;
int _V3GradientWidth;

int _AdvancedColorConfigurationEnabled;
float _Hue;
float _Saturation;
float _Value;
float _Brightness;
float _Contrast;
float _Gamma;
float _Exposure;
float _Transparency;

int4 MaskColor(uint2 id)
{
    uint width, height;
    _MaskTex.GetDimensions(width, height);

    uint2 maskUv = id.xy * _MaskTexScale;
    if (maskUv.x < 0 || maskUv.x >= width || maskUv.y < 0 || maskUv.y >= height) return int4(0, 0, 0, 0);

    int4 color = (int4)(LinearToGammaSpaceExact(_MaskTex[maskUv]) * 255.0);

    return color;
}

int4 ApplyMask(int4 source, int4 color, uint2 id)
{
    if (!_UseMask) return color;

    int4 maskColor = MaskColor(id);

    int4 backgroundColor = _IsBackgroundTransparent ? int4(0, 0, 0, 0) : source;

    if (_MaskSelectionType == 0)
    {
        return color;
    }

    if (_MaskSelectionType == 1 || _MaskSelectionType == 2) // GrayScale Mask
    {
        const float grayScaleWeightR = 0.299;
        const float grayScaleWeightG = 0.587;
        const float grayScaleWeightB = 0.114;

        float grayScale = (
            grayScaleWeightR * (maskColor.r / 255.0) +
            grayScaleWeightG * (maskColor.g / 255.0) +
            grayScaleWeightB * (maskColor.b / 255.0)
        );

        if (_IsBackgroundTransparent)
        {
            if (_MaskSelectionType == 1) // GrayScale Mask (Black)
            {
                return int4(color.rgb, (1 - grayScale) * 255.0);
            }
            else // GrayScale Mask (White)
            {
                return int4(color.rgb, grayScale * 255.0);
            }
        }
        else
        {
            if (_MaskSelectionType == 1) // GrayScale Mask (Black)
            {
                float alpha = 1 - grayScale;
                return int4(
                    (color.r * alpha + backgroundColor.r * (1 - alpha)),
                    (color.g * alpha + backgroundColor.g * (1 - alpha)),
                    (color.b * alpha + backgroundColor.b * (1 - alpha)),
                    255
                );
            }
            else // GrayScale Mask (White)
            {
                float alpha = grayScale;
                return int4(
                    (color.r * alpha + backgroundColor.r * (1 - alpha)),
                    (color.g * alpha + backgroundColor.g * (1 - alpha)),
                    (color.b * alpha + backgroundColor.b * (1 - alpha)),
                    255
                );
            }
        }
    }

    if (_MaskSelectionType == 3)
    {
        return (maskColor.a == 255) ? color : backgroundColor;
    }

    if (_MaskSelectionType == 4)
    {
        return (maskColor.a != 0) ? color : backgroundColor;
    }

    if (_MaskSelectionType == 5)
    {
        return (maskColor.a == 0) ? color : backgroundColor;
    }

    return backgroundColor;
}

[numthreads(16, 16, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    _TargetTex.GetDimensions(width, height);
    if (id.x >= width || id.y >= height) return;
    
    int4 sourceColor = (int4)(LinearToGammaSpaceExact(_SourceTex[id.xy]) * 255.0);
    int4 color = sourceColor;

    if (_ColorAdjustmentConfigurationEnabled)
    {
        if (_ColorMode == 0)
        {
            int3 colorOffset = (int3)_NormalTargetColor - (int3)_NormalSourceColor;
            color.rgb += colorOffset;
        }
        else
        {
            color.rgb = BalanceColorAdjustment(
                color.rgb,

                _ColorMode,

                (int3)_NormalSourceColor,
                (int3)_NormalTargetColor,

                _V1Weight,
                _V1Minimum,
                
                _V2Radius,
                _V2Weight,
                _V2Minimum,
                _V2IncludeOutside,

                _V3Gradient,
                _V3GradientWidth
            );
        }
    }

    if (_AdvancedColorConfigurationEnabled)
    {
        color = AdvancedColorAdjustment(
            color,
            _Hue,
            _Saturation,
            _Value,
            _Brightness,
            _Contrast,
            _Gamma,
            _Exposure,
            _Transparency
        );
    }

    color = ApplyMask(sourceColor, color, id.xy);
    _TargetTex[id.xy] = GammaToLinearSpaceExact(saturate(color / 255.0));
}
